"""videospec — IR déclarative : la vidéo comme donnée."""

from .models import (
    AbsolutePosition,
    Canvas,
    CountdownSegment,
    EyeOpenTransition,
    FileAsset,
    FootageSegment,
    GaugeSpec,
    HeadAnchor,
    ImageAsset,
    IntroSegment,
    NameplateSpec,
    NarrationSegment,
    SubtitleStyle,
    SubtitleTrack,
    TimerStyle,
    VideoAsset,
    VideoSpec,
    VoiceAsset,
    ZoomEffect,
)
from .ports import AssetResolver, RenderEngine, ResolvedAssets

__all__ = [
    "AbsolutePosition",
    "AssetResolver",
    "Canvas",
    "CountdownSegment",
    "EyeOpenTransition",
    "FileAsset",
    "FootageSegment",
    "GaugeSpec",
    "HeadAnchor",
    "ImageAsset",
    "IntroSegment",
    "NameplateSpec",
    "NarrationSegment",
    "RenderEngine",
    "ResolvedAssets",
    "SubtitleStyle",
    "SubtitleTrack",
    "TimerStyle",
    "VideoAsset",
    "VideoSpec",
    "VoiceAsset",
    "ZoomEffect",
]
